import "./globals.css";
import Providers from "@/redux/Providers";
import ProvidersTheme from "./providersTheme";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-mono">
        <Providers>
          <ProvidersTheme>{children}</ProvidersTheme>
        </Providers>
      </body>
    </html>
  );
}
